# Generated by Django 4.1.3 on 2022-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=275)),
                ('listiong_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=275)),
                ('email', models.EmailField(max_length=275)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=275)),
                ('message', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
