# Generated by Django 4.1.3 on 2022-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(choices=[('2', 2), ('1', 1), ('5', 5), ('4', 4), ('3', 3)], default='2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(choices=[('200000', '₹200000'), ('700000', '₹700000'), ('300000', '₹300000'), ('1000000', '₹1000000'), ('50000', '₹50000'), ('400000', '₹400000'), ('100000', '₹100000'), ('500000', '₹500000'), ('900000', '₹900000'), ('600000', '₹600000'), ('800000', '₹800000')], default='50000'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('CHG', 'Chhattisgarh'), ('BH', 'Bihar'), ('JAK', 'Jammu and Kashmir'), ('Rp', 'Raipur'), ('RCH', 'Ranchi'), ('MP', 'Maharashtra'), ('MP', 'Madya Pradesh'), ('HP', 'Himachal Pradesh'), ('HYD', 'Hyderabad'), ('GU', 'Gujarat'), ('H', 'Haryana'), ('KR', 'Karnataka'), ('G', 'Goa'), ('JK', 'Jharkhand'), ('OD', 'Orissa'), ('AP', 'Arunachal Pradesh'), ('AP', 'Andra Pradesh'), ('AS', 'Assam'), ('BP', 'Bhopal'), ('WB', 'West Bengal'), ('P', 'Patna'), ('KRL', 'Kerala')], default='WB', max_length=125),
        ),
    ]
